#!/bin/bash

sudo yum update -y

sudo yum install java-21
# supported are 11,17,21 so put 21 

sudo yum upgrade -y 

sudo yum install openjdk-17-jre -y

sudo wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
sudo yum upgrade
# Add required dependencies for the jenkins package
sudo yum install fontconfig java-17-openjdk
sudo yum install jenkins -y
sudo systemctl daemon-reload
sudo systemctl start jenkins
# sudo systemctl status jenkins
